[package]
name = "raytracer"
version = "0.1.0"
authors = ["Chris Allen <cma@bitemyapp.com>"]

[dependencies]
byteorder = "1.2.3"
rayon = "1.0.1"
stacker = "0.1.3"

[[bin]]
name = "raytracer"
path = "raytracer.rs"

[[bin]]
name = "testrs"
path = "test.rs"
